version: '3.8'

services:
  wine-concierge:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    volumes:
      - ./wine_business_info.txt:/app/wine_business_info.txt
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s